### PR TITLE
refactor(defaults): update to latest webpack-defaults

### PR DESCRIPTION
**Pull request by shellscape**
**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [x] CI related changes
- [x] Other... Please describe: webpack-defaults update

```
BREAKING CHANGE: Enforces `engines` of `"node": ">=6.9.0 < 7.0.0 || >= 8.9.0`
```

### CODE REVIEW

**Comment by danielosborn** [comment]
Thank you for updating this, very appreciative of your time! Will this update be included in the npm version as well, or should we expect a new release version for that?

**Comment by shellscape** [comment]
@danielosborn for the next release yes. but the PR doesn't introduce any functional changes. was there something from this PR that you were looking to leverage?

**Comment by danielosborn** [comment]
Just the Webpack v4 compatibility. I'm working on an on-going "starter" theme/workflow for new projects and we include jshint-loader for our build processes, and we're trying to upgrade that to use Webpack v4, but unless install directly from this repo, instead of through the NPM library, I don't get the Webpack v4 updates.

**Comment by petergraff** [comment]
I have the same issue--needing a webpack v4 compatible version from npm. Thanks for your work on this.

**Comment by motzko** [comment]
@shellscape do you have the ability to get this published to npm?

**Comment by shellscape** [comment]
@danielosborn @petergraff @motzko I'm confused about why you need a new version published. This PR (the one we're discussing in) was only metadata changes. Was there a previous PR that had changes to the code for webpack 4 that you need? Are you just seeing NPM install warnings or something?

I need more to go on that "webpack 4 compatibility" because that doesn't really tell me much.

**Comment by danielosborn** [comment]
@shellscape - Perhaps it was a previous PR, however this PR and #51 were referred to in #50. The NPM version is not yet compatible with Webpack v4 due to the error(s) reported in #51 and #50. 
In #50, you referred another commenter to this PR/commit. 
So perhaps we are commenting on the wrong PR, but either way, including from _this_ Github repo (it seemed to be after this PR was merged) includes the fixes for Webpack 4, while the NPM version does not.

**Comment by shellscape** [comment]
@danielosborn looks like I was mistaken to point that user to this PR. #51 looks to address issue #50. This PR (#53) doesn't really address that issue and was only a maintenance and metadata update. I've followed up with the author of #51 and hopefully they respond. We'll give it some time, but if they don't respond, we'll push through changes in a separate PR. I'd say moving forward that's the correct PR to comment on.

_It's possible that I had been referring to updated peerDependencies for webpack, but this PR doesn't appear to have affected any of the other dependencies, and it doesn't modify any code._

**Comment by petergraff** [comment]
Thanks for digging into this. For now, I'm just pointing to the github URL directly in my npm package file, so it's fine.

**Pull request merged**
