### PR TITLE
Webpack2

### PR DESCRIPTION
**Pull request by kostasmanionis**
Issue https://github.com/webpack-contrib/jshint-loader/issues/30

### CODE REVIEW

**Comment by kostasmanionis** [comment]
Hey @TheLarkInn, could you help me out with this failing test? The loader seems to be throwing an error, but the webpack build doesn't stop. Not sure why that is the case. Works fine in webpack1.

There's an issue about it here https://github.com/webpack-contrib/jshint-loader/issues/27 and there's a similar issue in eslint-loader too https://github.com/MoOx/eslint-loader/issues/136

**Comment by michael-ciniawsky** [comment]
@kostasmanionis Please close aand reopen the PR to trigger the CLA Bot and rebase against current master please

**Comment by kostasmanionis** [comment]
Closing. The readme seems to be updated. Will open up an updated PR if needed.

**Comment by michael-ciniawsky** [comment]
@kostasmanionis Thx nevertheless for chiming in, appreciated

**Pull request closed without merging**
